spring.application.name=nbc-w4-assignment
# datasource setup
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nbc_week4?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=jy
spring.datasource.password=1234
# hikari setup
spring.datasource.hikari.connectionTimeout=9000
spring.datasource.hikari.idleTimeout=9000
spring.datasource.hikari.maxLifetime=9000
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.minimumIdle=10